/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';


export const LOAD_CHANNEL_SUCCESS = 'LOAD_CHANNEL_SUCCESS';
export const LOAD_CHANNEL_FAILED = 'LOAD_CHANNEL_FAILED';
export const LOAD_CHANNEL= 'LOAD_CHANNEL';
export const ONCLICK_MODAL= 'ONCLICK_MODAL';
export const TOGGLE_CHANNEL_MODAL= 'TOGGLE_CHANNEL_MODAL';
export const SAVE_CHANNEL_SUCCESS = 'SAVE_CHANNEL_SUCCESS';
export const SAVE_CHANNEL_FAILED = 'SAVE_CHANNEL_FAILED';
export const SAVE_CHANNEL= 'SAVE_CHANNEL';


export const LOAD_SHOW_SUCCESS = 'LOAD_SHOW_SUCCESS';
export const LOAD_SHOW_FAILED = 'LOAD_SHOW_FAILED';
export const LOAD_SHOW= 'LOAD_SHOW';
export const TOGGLE_SHOW_MODAL= 'TOGGLE_SHOW_MODAL';
export const SAVE_SHOW_SUCCESS = 'SAVE_SHOW_SUCCESS';
export const SAVE_SHOW_FAILED = 'SAVE_SHOW_FAILED';
export const SAVE_SHOW= 'SAVE_SHOW';




export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';
export const LOAD_USERS= 'LOAD_USERS';

export const SAVE_USER_SUCCESS = 'SAVE_CHANNEL_SUCCESS';
export const SAVE_USER_FAILED = 'SAVE_CHANNEL_FAILED';
export const SAVE_USER= 'SAVE_CHANNEL';
export const TOGGLE_USER_MODAL= 'TOGGLE_USER_MODAL';




export const LOAD_EPISODE_SUCCESS = 'LOAD_EPISODE_SUCCESS';
export const LOAD_EPISODE_FAILED = 'LOAD_EPISODE_FAILED';
export const LOAD_EPISODE= 'LOAD_EPISODE';
export const TOGGLE_EPISODE_MODAL= 'TOGGLE_EPISODE_MODAL';
export const SAVE_EPISODE_SUCCESS = 'SAVE_EPISODE_SUCCESS';
export const SAVE_EPISODE_FAILED = 'SAVE_EPISODE_FAILED';
export const SAVE_EPISODE= 'SAVE_EPISODE';


