/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';


export const LOAD_CHANNEL_SUCCESS = 'LOAD_CHANNEL_SUCCESS';
export const LOAD_CHANNEL_FAILED = 'LOAD_CHANNEL_FAILED';
export const LOAD_CHANNEL= 'LOAD_CHANNEL';
export const ONCLICK_MODAL= 'ONCLICK_MODAL';
export const TOGGLE_CHANNEL_MODAL= 'TOGGLE_CHANNEL_MODAL';
export const SAVE_CHANNEL_SUCCESS = 'SAVE_CHANNEL_SUCCESS';
export const SAVE_CHANNEL_FAILED = 'SAVE_CHANNEL_FAILED';
export const SAVE_CHANNEL= 'SAVE_CHANNEL';
export const UPDATE_CHANNEL_SUCCESS = 'UPDATE_CHANNEL_SUCCESS';
export const UPDATE_CHANNEL_FAILED = 'UPDATE_CHANNEL_FAILED';
export const UPDATE_CHANNEL= 'UPDATE_CHANNEL';
export const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';
export const DELETE_CHANNEL_FAILED = 'DELETE_CHANNEL_FAILED';
export const DELETE_CHANNEL= 'DELETE_CHANNEL';
export const RESET_CHANNEL_NOTIFICATION ='RESET_CHANNEL_NOTIFICATION';


export const RESET_SHOW_NOTIFICATION = 'RESET_SHOW_NOTIFICATION';
export const LOAD_SHOW_SUCCESS = 'LOAD_SHOW_SUCCESS';
export const LOAD_SHOW_FAILED = 'LOAD_SHOW_FAILED';
export const LOAD_SHOW= 'LOAD_SHOW';
export const TOGGLE_SHOW_MODAL= 'TOGGLE_SHOW_MODAL';
export const SAVE_SHOW_SUCCESS = 'SAVE_SHOW_SUCCESS';
export const SAVE_SHOW_FAILED = 'SAVE_SHOW_FAILED';
export const SAVE_SHOW= 'SAVE_SHOW';
export const UPDATE_SHOW_SUCCESS = 'UPDATE_SHOW_SUCCESS';
export const UPDATE_SHOW_FAILED = 'UPDATE_SHOW_FAILED';
export const UPDATE_SHOW= 'UPDATE_SHOW';
export const DELETE_SHOW= 'DELETE_SHOW';
export const DELETE_SHOW_SUCCESS= 'DELETE_SHOW_SUCCESS';
export const DELETE_SHOW_FAILED= 'DELETE_SHOW_FAILED';

export const LOAD_COMPANY_BY_USER_FOR_SHOWS= 'LOAD_COMPANY_BY_USER_FOR_SHOWS';
export const LOAD_COMPANY_BY_USER_SUCCESS_FOR_SHOWS= 'LOAD_COMPANY_BY_USER_SUCCESS_FOR_SHOWS';
export const LOAD_COMPANY_BY_USER_FAILED_FOR_SHOWS= 'LOAD_COMPANY_BY_USER_FAILED_FOR_SHOWS';

export const LOAD_CHANNELS_FOR_SHOWS= 'LOAD_CHANNELS_FOR_SHOWS';
export const LOAD_CHANNELS_FOR_SHOWS_SUCCESS= 'LOAD_CHANNELS_FOR_SHOWS_SUCCESS';
export const LOAD_CHANNELS_FOR_SHOWS_FAILED= 'LOAD_CHANNELS_FOR_SHOWS_FAILED';

export const LOAD_COMPANY_BY_USER_FOR_CHANNEL= 'LOAD_COMPANY_BY_USER_FOR_CHANNEL';
export const LOAD_COMPANY_BY_USER_SUCCESS_FOR_CHANNEL= 'LOAD_COMPANY_BY_USER_SUCCESS_FOR_CHANNEL';
export const LOAD_COMPANY_BY_USER_FAILED_FOR_CHANNEL= 'LOAD_COMPANY_BY_USER_FAILED_FOR_CHANNEL';


export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';
export const LOAD_USERS= 'LOAD_USERS';
export const LOAD_COMPANY_BY_USER_FOR_USER= 'LOAD_COMPANY_BY_USER_FOR_USER';
export const LOAD_COMPANY_BY_USER_SUCCESS_FOR_USER= 'LOAD_COMPANY_BY_USER_SUCCESS_FOR_USER';

export const SAVE_USER_SUCCESS = 'SAVE_CHANNEL_SUCCESS';
export const SAVE_USER_FAILED = 'SAVE_CHANNEL_FAILED';
export const SAVE_USER= 'SAVE_CHANNEL';
export const TOGGLE_USER_MODAL= 'TOGGLE_USER_MODAL';





export const LOAD_COMPANY_SUCCESS = 'LOAD_COMPANY_SUCCESS';
export const LOAD_COMPANY_FAILED = 'LOAD_COMPANY_FAILED';
export const LOAD_COMPANY= 'LOAD_COMPANY';
export const TOGGLE_COMPANY_MODAL= 'TOGGLE_COMPANY_MODAL';
export const SAVE_COMPANY_SUCCESS = 'SAVE_COMPANY_SUCCESS';
export const SAVE_COMPANY_FAILED = 'SAVE_COMPANY_FAILED';
export const SAVE_COMPANY= 'SAVE_COMPANY';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILED = 'UPDATE_COMPANY_FAILED';
export const UPDATE_COMPANY= 'UPDATE_COMPANY';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_FAILED = 'DELETE_COMPANY_FAILED';
export const DELETE_COMPANY = 'DELETE_COMPANY';


export const LOAD_EPISODE_SUCCESS = 'LOAD_EPISODE_SUCCESS';
export const LOAD_EPISODE_FAILED = 'LOAD_EPISODE_FAILED';
export const LOAD_EPISODE= 'LOAD_EPISODE';
export const ONCLICK_EPISODE_MODAL= 'ONCLICK_EPISODE_MODAL';


export const TOGGLE_EPISODE_MODAL= 'TOGGLE_EPISODE_MODAL';
export const SAVE_EPISODE_SUCCESS = 'SAVE_EPISODE_SUCCESS';
export const SAVE_EPISODE_FAILED = 'SAVE_EPISODE_FAILED';
export const SAVE_EPISODE= 'SAVE_EPISODE';
export const UPDATE_EPISODE_SUCCESS = 'UPDATE_EPISODE_SUCCESS';
export const UPDATE_EPISODE_FAILED = 'UPDATE_EPISODE_FAILED';
export const UPDATE_EPISODE= 'UPDATE_EPISODE';
export const DELETE_EPISODE_SUCCESS = 'DELETE_EPISODE_SUCCESS';
export const DELETE_EPISODE_FAILED = 'DELETE_EPISODE_FAILED';
export const DELETE_EPISODE = 'DELETE_EPISODE';


export const SEARCH_EPISODE_SUCCESS = 'SEARCH_EPISODE_SUCCESS';
export const SEARCH_EPISODE= 'SEARCH_EPISODE';


export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS';
export const RESET_USER_NOTIFICATION= 'RESET_USER_NOTIFICATION';


export const RESET_COMPANY_NOTIFICATION = 'RESET_COMPANY_NOTIFICATION';




//SEARCH_EPISODE, SEARCH_EPISODE_SUCCESS